ViWrap installation updates
AnantharamanLab/ViWrap pull request #1
Opened 2023-01-09 20:44 UTC by cody-mar10

1. fixed a common python bug checking membership of multiple items in `scripts/downloadDB.py`
2. fixed silent installation errors in `scripts/master_set_up_env.py`
3. Changed installation wording since it is not explicitly required to install all the ends in a separate location. This is something specific to our server setup.

2023-01-11 16:34 UTC, cody-mar10 commented
Adjusted the choice of color palette to prevent reusing the same colors for plots in `scripts/run_Visualizations.py`

2023-01-13 01:35 UTC, ChaoLab reviewed
I re-organize the information on this part

2023-01-13 01:44 UTC, ChaoLab approved these changes

2023-01-13 01:45 UTC, ChaoLab requested changes
I accept the changes

2023-01-13 01:45 UTC, ChaoLab approved these changes

2023-01-13 01:48 UTC, ChaoLab approved these changes

2023-01-13 01:48 UTC, ChaoLab approved these changes

2023-01-13 01:48 UTC, ChaoLab approved these changes

2023-01-13 01:48 UTC, ChaoLab approved these changes

2023-01-13 01:48 UTC, ChaoLab approved these changes

2023-01-13 01:51 UTC, ChaoLab approved these changes

2023-01-13 01:53 UTC, ChaoLab approved these changes

2023-01-13 01:55 UTC, merged